steps:
# ==========================================
# 1. BUILD AND DEPLOY THE BACKEND
# ==========================================
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/todo-repo/todo-backend', './backend']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/todo-repo/todo-backend']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'todo-backend'
  - '--image'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/todo-repo/todo-backend'
  - '--region'
  - 'us-central1'
  - '--allow-unauthenticated'
  - '--port'
  - '5001'

# ==========================================
# 2. BUILD AND DEPLOY THE FRONTEND
# ==========================================
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/todo-repo/todo-frontend', './frontend']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/todo-repo/todo-frontend']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'todo-frontend'
  - '--image'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/todo-repo/todo-frontend'
  - '--region'
  - 'us-central1'
  - '--allow-unauthenticated'
  - '--port'
  - '80'

options:
  logging: CLOUD_LOGGING_ONLY